version: "3.8"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: volnei
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_user
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@contele.com"
      PGADMIN_DEFAULT_PASSWORD: "contele"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db-data:
    external: true
