version: "3.8"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    container_name: db_postgres
    hostname: postgres_knex
    image: postgres:14.2
    environment:
      POSTGRES_USER: volnei
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_user
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes: 
  db-data: