version: "3.8"
services:
  app:
    build: .
    container_name: app
    command: sh -c "npm start"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app    
    links:
      - db 
    depends_on:
      - db
    environment:
      DATABASE_URL: host.docker.internal
  db:
    image: postgres:14.2
    container_name: database_user
    environment:
      POSTGRES_USER: volnei
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: db_user
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
